# This is an example docker-compose file
version: "3.4"

services:
  cucumber_reporter:
    image: cucumber-google-sheets:latest
    volumes:
      - ./cucumber-messages.json:/data/cucumber-messages.json
      - ./google-api-keys.json:/data/google-api-keys.json
      - ./output.csv:/data/output.csv
    environment:
      - GOOGLE_SHEET_ID=1qOOvhfOXmeh-ERCY9gXINQVa2Yn_gMkCxs1VW5DPx9c
      - OUTPUT_CSV=false
      - OUTPUT_GOOGLE=true
